# Generated by Django 5.2.4 on 2025-07-31 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMPLOY',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_mob', models.CharField(max_length=100)),
                ('emp_doj', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
