# Generated by Django 5.2.4 on 2025-07-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EMPLOYEE',
            new_name='EMPLOYEES',
        ),
    ]
