# Generated by Django 5.2.4 on 2025-07-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0003_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EMPLOYEES',
        ),
    ]
