# Generated by Django 5.2.4 on 2025-07-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0004_delete_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMPLOYEES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
