# Generated by Django 5.2.4 on 2025-07-29 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0005_employees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STUDENTS',
        ),
    ]
