# Generated by Django 5.2.4 on 2025-07-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0006_delete_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='name',
            field=models.CharField(default='employee', max_length=100),
        ),
        migrations.AddField(
            model_name='employees',
            name='phone',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
