# Generated by Django 5.2.4 on 2025-07-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMPLOYEE',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_age', models.IntegerField()),
            ],
        ),
    ]
